# Generated by Django 5.1.1 on 2024-10-04 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rate', models.IntegerField()),
                ('from_place', models.CharField(max_length=20)),
                ('to_place', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'booking_table',
            },
        ),
    ]
