# Generated by Django 5.1.1 on 2024-10-04 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='from_place_tamil',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
